name: Build Module

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Upload Asset
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Get Id
        id: mId
        run: echo "::set-output name=id::$(grep "^id=" module.prop|cut -d'=' -f2)"
        
      - name: Get Version
        id: mVersion
        run: echo "::set-output name=version::$(grep "^version=" module.prop|cut -d'=' -f2)"

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: zip -r "${{ steps.mId.outputs.id }}.v${{ steps.mVersion.outputs.version }}.zip" . -x "README.md" ".git/*" ".github/*" 

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.mVersion.outputs.version }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./${{ steps.mId.outputs.id }}.v${{ steps.mVersion.outputs.version }}.zip
          asset_name: ${{ steps.mId.outputs.id }}.v${{ steps.mVersion.outputs.version }}.zip
          asset_content_type: application/zip
